[tool.poetry]
name = "bettermonitoring"
version = "0.1.2"
description = ""
authors = ["Roman"]

[tool.poetry.dependencies]
python = "^3.10"
httpx = "^0.22.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
